language: ruby
rvm:
  - 2.1
install:
  - bundle install
script:
  - bundle exec rake jekyll_build
  - bundle exec rake check_html
branches:
  only:
    - master
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
