language: ruby
rvm:
  - 2.1
before_script:
  - npm install -g bower
  - bower install
install:
  - bundle install
script:
  - bundle exec rake jekyll_build
  - bundle exec rake check_html
branches:
  only:
    - master
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - RACK_ENV=test
