---

language: ruby
sudo: false
addons:
  apt:
    packages:
      - default-jre-headless
      - libgsl0-dev
cache: bundler
before_script:
  - npm install
  - wget --quiet https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/htmlcompressor/htmlcompressor-1.5.3.jar
  - wget --quiet https://github.com/yui/yuicompressor/releases/download/v2.4.8/yuicompressor-2.4.8.jar
  - mv *.jar /tmp && mkdir -p ./_bin
  - echo 'exec java -jar /tmp/htmlcompressor-1.5.3.jar "$@"' > ./_bin/htmlcompressor
  - echo 'exec java -jar /tmp/yuicompressor-2.4.8.jar "$@"' > ./_bin/yuicompressor
  - chmod +x ./_bin/htmlcompressor ./_bin/yuicompressor
install:
  - bundle install
script:
  - bundle exec rake build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: _build
  target_branch: gh-pages
  name: Travis-CI
  on:
    branch: master
  branches:
    only:
      - master
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - JEKYLL_ENV=production
    - PATH="$PATH:$PWD/_bin"
    - secure: HHn4fB95S+0AmpLwH6z/yc2OHl8ZWj2BLZiJomEf2or6sJHc1AvDz/6scseXMip4KEt+jd0hICuJ32VkuYq7VUk3dDg/PRMiIVODPxis2x4amtx04HmMn1ZY7BKubLGuIK30YdkxG3dzVrRk/HDEshO8aE+/x6y90SSlIJ/hJB8=
