---
language: ruby
sudo: false
addons:
  apt:
    packages:
      - libgsl0-dev
cache:
  bundler: true
  npm: true
before_script:
  - npm install
install:
  - bundle install
script:
  - bundle exec rake build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: _build
  target_branch: gh-pages
  name: Travis-CI
  on:
    branch: master
  branches:
    only:
      - master
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - JEKYLL_ENV=production
    - PATH="$PATH:$PWD/_bin"
    - secure: bovQFbxlxqoY66Ti4mVyQEaPJ28SUX/FShZkGeZU+K0p8bE1qp4E0h1ApfdQmxEpHlN0hYsRToSvEH43S6HlVT5yc9HRLqibIvb1YBYPo/mgIKB0OtquhDGGZAq+VOKznhGy96CwjgNCeIj2wcQddGAASkJq/IF3uTZVPUyq+ew=
