name: ./runner.sh
url: http://runner.sh
author: "Benjamin Dos Santos"
email: "benjamin[dot]dossantos[at]gmail[dot]com"
timezone: Europe/Paris
markdown: redcarpet
redcarpet:
  extensions: [
    'no_intra_emphasis', 'fenced_code_blocks',
    'autolink', 'tables', 'with_toc_data'
  ]
pygments: false
future: false
exclude: ['Rakefile', 'Gemfile*', ]
permalink: /:year/:month/:day/:title.html
google_verify: 'J4i94TW6V0a5ka7ZluORmLjmPWkMZNm67tOjXuDyB0I'
google_analytics: 'UA-9203113-5'

links:
  - title: Blog
    url: /
  - title: A propos
    url: /about.html
  - title: Todo-list
    url: /todo-list.html
  - title: Archives
    url: /archives.html
