name: bds.run
url: http://bds.run
author: "Benjamin Dos Santos"
email: "benjamin[dot]dossantos[at]gmail[dot]com"
timezone: Europe/Paris
markdown: kramdown
highlighter: false
future: false
lsi: true
exclude: ['README.md', 'Rakefile', 'Gemfile*', 'bower.json', ]
gems: ['jekyll_image_encode', 'jekyll-assets', 'jekyll-sitemap', ]
permalink: /:year/:month/:day/:title.html
google_verify: 'J4i94TW6V0a5ka7ZluORmLjmPWkMZNm67tOjXuDyB0I'
google_analytics: 'UA-9203113-5'
twitter: 'benjamin_ds'
assets:
  cache: true
  dirname: assets
  baseurl: /assets/
  cachebust: hard
  css_compressor: yui
  js_compressor: yui
  sources:
    - _assets/images
    - _assets/stylesheets
    - _assets/javascripts
    - _bower
links:
  - title: Blog
    url: /
  - title: A propos
    url: /about.html
  - title: Todo-list
    url: /todo-list.html
  - title: Archives
    url: /archives.html
