---

name: bds.run
url: https://bds.run
author: 'Benjamin Dos Santos'
email: 'benjamin[dot]dossantos[at]gmail[dot]com'
timezone: Europe/Paris
markdown: kramdown
highlighter: rouge
future: false
lsi: false
exclude:
  - Dockerfile
  - Gemfile*
  - README.md
  - Rakefile
  - bower.json
  - docker-compose.yml
plugins:
  - jekyll-assets
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll_image_encode
permalink: /:year/:month/:day/:title.html
google_verify: 'J4i94TW6V0a5ka7ZluORmLjmPWkMZNm67tOjXuDyB0I'
google_analytics: 'UA-9203113-5'
twitter:
  username: benjamin_ds
social:
  name: Benjamin Dos Santos
  links:
    - https://twitter.com/benjamin_ds
    - https://www.facebook.com/benjamin.ds
    - https://www.linkedin.com/in/benjaminds
    - https://plus.google.com/+BenjaminDosSantos
    - https://github.com/bdossantos
    - https://keybase.io/bdossantos
    - https://www.strava.com/athletes/6925704
google_site_verification: 'J4i94TW6V0a5ka7ZluORmLjmPWkMZNm67tOjXuDyB0I'
assets:
  caching:
    path: '.jekyll-cache/assets'
    type: memory
    enabled: true
  compression: true
  digest: false
  dirname: assets
  prefix: /assets/
  sources:
    - _assets/images
    - _assets/stylesheets
    - _assets/javascripts
    - _bower
  plugins:
    img: {optim: {}}
  gzip: true
links:
  - title: Blog
    url: /
  - title: Archives
    url: /archives.html
  - title: CV
    url: /cv.html
feed:
  path: atom.xml
