name: bds.run
url: http://bds.run
author: 'Benjamin Dos Santos'
email: 'benjamin[dot]dossantos[at]gmail[dot]com'
timezone: Europe/Paris
markdown: kramdown
highlighter: rouge
future: false
lsi: true
exclude:
  - Dockerfile
  - Gemfile*
  - README.md
  - Rakefile
  - bower.json
  - docker-compose.yml
gems:
  - jekyll-assets
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll_image_encode
permalink: /:year/:month/:day/:title.html
google_verify: 'J4i94TW6V0a5ka7ZluORmLjmPWkMZNm67tOjXuDyB0I'
google_analytics: 'UA-9203113-5'
twitter: 'benjamin_ds'
assets:
  cache: .asset-cache
  dirname: assets
  prefix: /assets/
  sources:
    - _assets/images
    - _assets/stylesheets
    - _assets/javascripts
    - _bower
  features:
    automatic_image_size: true
    automatic_image_alt : true
links:
  - title: Blog
    url: /
  - title: A propos
    url: /about.html
  - title: Todo-list
    url: /todo-list.html
  - title: Archives
    url: /archives.html
feed:
  path: atom.xml
