name: Running plans
timezone: Europe/Paris
markdown: redcarpet
redcarpet:
  extensions: [
    'no_intra_emphasis', 'fenced_code_blocks',
    'autolink', 'tables', 'with_toc_data'
  ]
pygments: false
future: false
permalink: /:title.html
