source 'https://rubygems.org'

gem 'classifier-reborn'
gem 'gsl'
gem 'html-proofer'
gem 'image_optim'
gem 'image_optim_pack'
gem 'jekyll'
gem 'jekyll-assets', :git => 'https://github.com/kou/jekyll-assets.git', :branch => 'add-support-for-sprockets-4.0'
gem 'jekyll-feed'
gem 'jekyll-redirect-from'
gem 'jekyll-seo-tag'
gem 'jekyll-sitemap'
gem 'jekyll_image_encode'
gem 'mini_magick'
gem 'rake'
gem 'sass'
gem 'strava-api-v3'
gem 'uglifier'
