---
name: CI

on:
  push:
    #branches: [master]
  pull_request:
    #branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          rubygems: 3.4.7
      - uses: actions/setup-node@v3
        with:
          cache: npm
      - name: Build
        run: |
          env JEKYLL_ENV=production bundle exec rake build
      - name: Deploy 🚀
        if: github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: _build
